influxsrv:
  image: influxdb:latest
  container_name: influxsrv
  ports:
    - "8086:8086"
  volumes:
    - influxdata:/var/lib/influxdb:rw

grafana:
  build: ./grafana
  container_name: grafana
  ports:
    - "80:3000"
  links:
    - influxsrv:influxsrv
  volumes:
    - grafanadb:/var/lib/grafana
  environment:
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=rspengines
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root

notebook:
  image: jupyter/minimal-notebook
  links:
    - influxsrv:influxsrv
    - grafana:grafana
  ports:
    8888:8888
  volumes:
    - /home/rspdev/rsplib/:/home/jovyan/work
    - resultsdata:/home/jovyan/work/data
